//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT4.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GT4.UI.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete {0}?.
        /// </summary>
        public static string AlertTextDeleteConfirmationText_1 {
            get {
                return ResourceManager.GetString("AlertTextDeleteConfirmationText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add name for the &apos;{0}&apos; biological sex.
        /// </summary>
        public static string AlertTextUnableToAddNameForTheSexSelected_1 {
            get {
                return ResourceManager.GetString("AlertTextUnableToAddNameForTheSexSelected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string AlertTitleConfirmation {
            get {
                return ResourceManager.GetString("AlertTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛔ Error.
        /// </summary>
        public static string AlertTitleError {
            get {
                return ResourceManager.GetString("AlertTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ Info.
        /// </summary>
        public static string AlertTitleInfo {
            get {
                return ResourceManager.GetString("AlertTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Warning.
        /// </summary>
        public static string AlertTitleWarning {
            get {
                return ResourceManager.GetString("AlertTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genealogy Tree 4.
        /// </summary>
        public static string AppGeneralName {
            get {
                return ResourceManager.GetString("AppGeneralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own
        ///genealogy tree and enjoy!.
        /// </summary>
        public static string AppGeneralWelcomeTitle {
            get {
                return ResourceManager.GetString("AppGeneralWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♀ Woman.
        /// </summary>
        public static string BiologicalSexFemale {
            get {
                return ResourceManager.GetString("BiologicalSexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♂ Man.
        /// </summary>
        public static string BiologicalSexMale {
            get {
                return ResourceManager.GetString("BiologicalSexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚧️ Human.
        /// </summary>
        public static string BiologicalSexUnknown {
            get {
                return ResourceManager.GetString("BiologicalSexUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add name.
        /// </summary>
        public static string BtnNameAddPersonName {
            get {
                return ResourceManager.GetString("BtnNameAddPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string BtnNameAddPersonPhoto {
            get {
                return ResourceManager.GetString("BtnNameAddPersonPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add relationship.
        /// </summary>
        public static string BtnNameAddPersonRelationship {
            get {
                return ResourceManager.GetString("BtnNameAddPersonRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnNameCancel {
            get {
                return ResourceManager.GetString("BtnNameCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Family.
        /// </summary>
        public static string BtnNameCreateFamily {
            get {
                return ResourceManager.GetString("BtnNameCreateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Person.
        /// </summary>
        public static string BtnNameCreateFamilyPerson {
            get {
                return ResourceManager.GetString("BtnNameCreateFamilyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Genealogy Tree.
        /// </summary>
        public static string BtnNameCreateGenealogyTree {
            get {
                return ResourceManager.GetString("BtnNameCreateGenealogyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a {0}.
        /// </summary>
        public static string BtnNameCreateName_1 {
            get {
                return ResourceManager.GetString("BtnNameCreateName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string BtnNameMarkdownEditor {
            get {
                return ResourceManager.GetString("BtnNameMarkdownEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string BtnNameMarkdownView {
            get {
                return ResourceManager.GetString("BtnNameMarkdownView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNameNo {
            get {
                return ResourceManager.GetString("BtnNameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BtnNameOk {
            get {
                return ResourceManager.GetString("BtnNameOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Create.
        /// </summary>
        public static string BtnNameOpenOrCreateProject {
            get {
                return ResourceManager.GetString("BtnNameOpenOrCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Refresh?.
        /// </summary>
        public static string BtnNameRefreshAfterError {
            get {
                return ResourceManager.GetString("BtnNameRefreshAfterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the Person.
        /// </summary>
        public static string BtnNameUpdateFamilyPerson {
            get {
                return ResourceManager.GetString("BtnNameUpdateFamilyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Genealogy Tree.
        /// </summary>
        public static string BtnNameUpdateGenealogyTree {
            get {
                return ResourceManager.GetString("BtnNameUpdateGenealogyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the {0}.
        /// </summary>
        public static string BtnNameUpdateName_1 {
            get {
                return ResourceManager.GetString("BtnNameUpdateName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnNameYes {
            get {
                return ResourceManager.GetString("BtnNameYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is known approximately.
        /// </summary>
        public static string DateKnownApproximately {
            get {
                return ResourceManager.GetString("DateKnownApproximately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not defined.
        /// </summary>
        public static string DateStatusNotDefined {
            get {
                return ResourceManager.GetString("DateStatusNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string DateStatusUnknown {
            get {
                return ResourceManager.GetString("DateStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0}.
        /// </summary>
        public static string DateStatusYearApproximate_1 {
            get {
                return ResourceManager.GetString("DateStatusYearApproximate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least the following persons share name {0}: {1}.
        /// </summary>
        public static string ErrorNameIsShared_2 {
            get {
                return ResourceManager.GetString("ErrorNameIsShared_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection limit has been reached..
        /// </summary>
        public static string ErrorTheBoundIsReached {
            get {
                return ResourceManager.GetString("ErrorTheBoundIsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string FieldAge {
            get {
                return ResourceManager.GetString("FieldAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological sex.
        /// </summary>
        public static string FieldBiologicalSex {
            get {
                return ResourceManager.GetString("FieldBiologicalSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common person name format.
        /// </summary>
        public static string FieldCommonPersonNameFormat {
            get {
                return ResourceManager.GetString("FieldCommonPersonNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full date display format.
        /// </summary>
        public static string FieldDateDisplayFormat {
            get {
                return ResourceManager.GetString("FieldDateDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY - year
        ///MM - month number (01-12)
        ///MMM - month name (January - December)
        ///DD - day number (01-31).
        /// </summary>
        public static string FieldDateDisplayFormatHint {
            get {
                return ResourceManager.GetString("FieldDateDisplayFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date entered.
        /// </summary>
        public static string FieldDateEntered {
            get {
                return ResourceManager.GetString("FieldDateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string FieldDateOfBirth {
            get {
                return ResourceManager.GetString("FieldDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of death:.
        /// </summary>
        public static string FieldDateOfDeath {
            get {
                return ResourceManager.GetString("FieldDateOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string FieldDay {
            get {
                return ResourceManager.GetString("FieldDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FieldFamilyName {
            get {
                return ResourceManager.GetString("FieldFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string FieldFamilyNameEntry {
            get {
                return ResourceManager.GetString("FieldFamilyNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FieldFirstName {
            get {
                return ResourceManager.GetString("FieldFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female first name.
        /// </summary>
        public static string FieldFirstNameFemaleEntry {
            get {
                return ResourceManager.GetString("FieldFirstNameFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male first name.
        /// </summary>
        public static string FieldFirstNameMaleEntry {
            get {
                return ResourceManager.GetString("FieldFirstNameMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full person name format.
        /// </summary>
        public static string FieldFullPersonNameFormat {
            get {
                return ResourceManager.GetString("FieldFullPersonNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string FieldLastName {
            get {
                return ResourceManager.GetString("FieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name in the female declension.
        /// </summary>
        public static string FieldLastNameFemaleEntry {
            get {
                return ResourceManager.GetString("FieldLastNameFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name in the male declension.
        /// </summary>
        public static string FieldLastNameMaleEntry {
            get {
                return ResourceManager.GetString("FieldLastNameMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string FieldMonth {
            get {
                return ResourceManager.GetString("FieldMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string FieldPatronymic {
            get {
                return ResourceManager.GetString("FieldPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female patronymic.
        /// </summary>
        public static string FieldPatronymicFemaleEntry {
            get {
                return ResourceManager.GetString("FieldPatronymicFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male patronymic.
        /// </summary>
        public static string FieldPatronymicMaleEntry {
            get {
                return ResourceManager.GetString("FieldPatronymicMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string FieldPersonBiography {
            get {
                return ResourceManager.GetString("FieldPersonBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string FieldPersonDates {
            get {
                return ResourceManager.GetString("FieldPersonDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person initials format.
        /// </summary>
        public static string FieldPersonInitialsFormat {
            get {
                return ResourceManager.GetString("FieldPersonInitialsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF - first name,              FF. - first name initial
        ///PP - patronymic,          PP. - patronymic initial
        ///LL - last name,               LL. - last name initial
        ///FN - family name.
        /// </summary>
        public static string FieldPersonNameFormatHint {
            get {
                return ResourceManager.GetString("FieldPersonNameFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string FieldPersonNames {
            get {
                return ResourceManager.GetString("FieldPersonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string FieldPersonPhotos {
            get {
                return ResourceManager.GetString("FieldPersonPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string FieldPersonRelationships {
            get {
                return ResourceManager.GetString("FieldPersonRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string FieldRelationshipStartDate {
            get {
                return ResourceManager.GetString("FieldRelationshipStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of relationship.
        /// </summary>
        public static string FieldRelationshipType {
            get {
                return ResourceManager.GetString("FieldRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision: {0}.
        /// </summary>
        public static string FieldRevision_1 {
            get {
                return ResourceManager.GetString("FieldRevision_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string FieldSearchText {
            get {
                return ResourceManager.GetString("FieldSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FieldSelectName {
            get {
                return ResourceManager.GetString("FieldSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select name type.
        /// </summary>
        public static string FieldSelectNameType {
            get {
                return ResourceManager.GetString("FieldSelectNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short date display format.
        /// </summary>
        public static string FieldShortDateDisplayFormat {
            get {
                return ResourceManager.GetString("FieldShortDateDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY - year
        ///MM - month number (01-12)
        ///MMM - month name (January - December).
        /// </summary>
        public static string FieldShortDateDisplayFormatHint {
            get {
                return ResourceManager.GetString("FieldShortDateDisplayFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string FieldYear {
            get {
                return ResourceManager.GetString("FieldYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pictures.
        /// </summary>
        public static string FileDialogSelectPictures {
            get {
                return ResourceManager.GetString("FileDialogSelectPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or create family.
        /// </summary>
        public static string HintFamiliesPage {
            get {
                return ResourceManager.GetString("HintFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open family member or create a new one.
        /// </summary>
        public static string HintFamilyPage {
            get {
                return ResourceManager.GetString("HintFamilyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add, edit or delete the names of any person..
        /// </summary>
        public static string HintNamesPage {
            get {
                return ResourceManager.GetString("HintNamesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or create a new one.
        /// </summary>
        public static string HintProjectPage {
            get {
                return ResourceManager.GetString("HintProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👪 To family: {0}.
        /// </summary>
        public static string MenuItemGotoFamily_1 {
            get {
                return ResourceManager.GetString("MenuItemGotoFamily_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 To Names.
        /// </summary>
        public static string MenuItemGoToNames {
            get {
                return ResourceManager.GetString("MenuItemGoToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Create a Person.
        /// </summary>
        public static string MenuItemNameAddPerson {
            get {
                return ResourceManager.GetString("MenuItemNameAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Create a Family.
        /// </summary>
        public static string MenuItemNameCreateFamily {
            get {
                return ResourceManager.GetString("MenuItemNameCreateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Create a Genealogy Tree.
        /// </summary>
        public static string MenuItemNameCreateGenealogyTree {
            get {
                return ResourceManager.GetString("MenuItemNameCreateGenealogyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖋️ Edit &apos;{0}&apos;.
        /// </summary>
        public static string MenuItemNameEdit_1 {
            get {
                return ResourceManager.GetString("MenuItemNameEdit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄️ Refresh.
        /// </summary>
        public static string MenuItemNameRefresh {
            get {
                return ResourceManager.GetString("MenuItemNameRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Remove &apos;{0}&apos;.
        /// </summary>
        public static string MenuItemNameRemove_1 {
            get {
                return ResourceManager.GetString("MenuItemNameRemove_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Settings.
        /// </summary>
        public static string MenuItemNameSettings {
            get {
                return ResourceManager.GetString("MenuItemNameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Month_01 {
            get {
                return ResourceManager.GetString("Month_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabruary.
        /// </summary>
        public static string Month_02 {
            get {
                return ResourceManager.GetString("Month_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Month_03 {
            get {
                return ResourceManager.GetString("Month_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Month_04 {
            get {
                return ResourceManager.GetString("Month_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month_05 {
            get {
                return ResourceManager.GetString("Month_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Month_06 {
            get {
                return ResourceManager.GetString("Month_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Month_07 {
            get {
                return ResourceManager.GetString("Month_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Month_08 {
            get {
                return ResourceManager.GetString("Month_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Month_09 {
            get {
                return ResourceManager.GetString("Month_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Month_10 {
            get {
                return ResourceManager.GetString("Month_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Month_11 {
            get {
                return ResourceManager.GetString("Month_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Month_12 {
            get {
                return ResourceManager.GetString("Month_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string NameFamily {
            get {
                return ResourceManager.GetString("NameFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string NameFirst {
            get {
                return ResourceManager.GetString("NameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string NameLast {
            get {
                return ResourceManager.GetString("NameLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string NamePatronymic {
            get {
                return ResourceManager.GetString("NamePatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string PersonAge_2 {
            get {
                return ResourceManager.GetString("PersonAge_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string PersonDates_2 {
            get {
                return ResourceManager.GetString("PersonDates_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to † {0}.
        /// </summary>
        public static string PersonDeathMark_1 {
            get {
                return ResourceManager.GetString("PersonDeathMark_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} since birth.
        /// </summary>
        public static string PersonSinceBirthDay_1 {
            get {
                return ResourceManager.GetString("PersonSinceBirthDay_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language.
        /// </summary>
        public static string PkrLanguageHint {
            get {
                return ResourceManager.GetString("PkrLanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} once removed.
        /// </summary>
        public static string Rel1Removed_en_1 {
            get {
                return ResourceManager.GetString("Rel1Removed_en_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second {0}.
        /// </summary>
        public static string Rel2Female_1 {
            get {
                return ResourceManager.GetString("Rel2Female_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second {0}.
        /// </summary>
        public static string Rel2Male_1 {
            get {
                return ResourceManager.GetString("Rel2Male_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} twice removed.
        /// </summary>
        public static string Rel2Removed_en_1 {
            get {
                return ResourceManager.GetString("Rel2Removed_en_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second {0}.
        /// </summary>
        public static string Rel2Unknown_1 {
            get {
                return ResourceManager.GetString("Rel2Unknown_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third {0}.
        /// </summary>
        public static string Rel3Female_1 {
            get {
                return ResourceManager.GetString("Rel3Female_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third {0}.
        /// </summary>
        public static string Rel3Male_1 {
            get {
                return ResourceManager.GetString("Rel3Male_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trice removed .
        /// </summary>
        public static string Rel3Removed_en_1 {
            get {
                return ResourceManager.GetString("Rel3Removed_en_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third {0}.
        /// </summary>
        public static string Rel3Unknown_1 {
            get {
                return ResourceManager.GetString("Rel3Unknown_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth {0}.
        /// </summary>
        public static string Rel4Female_1 {
            get {
                return ResourceManager.GetString("Rel4Female_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth {0}.
        /// </summary>
        public static string Rel4Male_1 {
            get {
                return ResourceManager.GetString("Rel4Male_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth {0}.
        /// </summary>
        public static string Rel4Unknown_1 {
            get {
                return ResourceManager.GetString("Rel4Unknown_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoptive {0}.
        /// </summary>
        public static string RelAdoptiveFemale_1 {
            get {
                return ResourceManager.GetString("RelAdoptiveFemale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoptive {0}.
        /// </summary>
        public static string RelAdoptiveInvariant_1 {
            get {
                return ResourceManager.GetString("RelAdoptiveInvariant_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoptive {0}.
        /// </summary>
        public static string RelAdoptiveMale_1 {
            get {
                return ResourceManager.GetString("RelAdoptiveMale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aunt.
        /// </summary>
        public static string RelAunt {
            get {
                return ResourceManager.GetString("RelAunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        public static string RelBrother {
            get {
                return ResourceManager.GetString("RelBrother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string RelChild {
            get {
                return ResourceManager.GetString("RelChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child-in-law.
        /// </summary>
        public static string RelChildInLaw {
            get {
                return ResourceManager.GetString("RelChildInLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cousin.
        /// </summary>
        public static string RelCousin_en {
            get {
                return ResourceManager.GetString("RelCousin_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter.
        /// </summary>
        public static string RelDaughter {
            get {
                return ResourceManager.GetString("RelDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter-in-law.
        /// </summary>
        public static string RelDaughterInLaw {
            get {
                return ResourceManager.GetString("RelDaughterInLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string RelFather {
            get {
                return ResourceManager.GetString("RelFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand aunt.
        /// </summary>
        public static string RelGrandAunt_en {
            get {
                return ResourceManager.GetString("RelGrandAunt_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandchild.
        /// </summary>
        public static string RelGrandChild {
            get {
                return ResourceManager.GetString("RelGrandChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granddaughter.
        /// </summary>
        public static string RelGrandDaughter {
            get {
                return ResourceManager.GetString("RelGrandDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandfather.
        /// </summary>
        public static string RelGrandFather {
            get {
                return ResourceManager.GetString("RelGrandFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandmother.
        /// </summary>
        public static string RelGrandMother {
            get {
                return ResourceManager.GetString("RelGrandMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandnephew.
        /// </summary>
        public static string RelGrandNephew_en {
            get {
                return ResourceManager.GetString("RelGrandNephew_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand nephew or niece.
        /// </summary>
        public static string RelGrandNephewNiece_en {
            get {
                return ResourceManager.GetString("RelGrandNephewNiece_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandniece.
        /// </summary>
        public static string RelGrandNiece_en {
            get {
                return ResourceManager.GetString("RelGrandNiece_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandparent.
        /// </summary>
        public static string RelGrandParent {
            get {
                return ResourceManager.GetString("RelGrandParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandson.
        /// </summary>
        public static string RelGrandSon {
            get {
                return ResourceManager.GetString("RelGrandSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand uncle.
        /// </summary>
        public static string RelGrandUncle_en {
            get {
                return ResourceManager.GetString("RelGrandUncle_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand uncle or aunt.
        /// </summary>
        public static string RelGrandUncleAunt_en {
            get {
                return ResourceManager.GetString("RelGrandUncleAunt_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great-{0}.
        /// </summary>
        public static string RelGreat_1 {
            get {
                return ResourceManager.GetString("RelGreat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        public static string RelHusband {
            get {
                return ResourceManager.GetString("RelHusband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-law.
        /// </summary>
        public static string RelInLawFemale {
            get {
                return ResourceManager.GetString("RelInLawFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-law.
        /// </summary>
        public static string RelInLawMale {
            get {
                return ResourceManager.GetString("RelInLawMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-law.
        /// </summary>
        public static string RelInLawUnknown {
            get {
                return ResourceManager.GetString("RelInLawUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternal {0}.
        /// </summary>
        public static string RelMaternal_1 {
            get {
                return ResourceManager.GetString("RelMaternal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string RelMother {
            get {
                return ResourceManager.GetString("RelMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nephew.
        /// </summary>
        public static string RelNephew {
            get {
                return ResourceManager.GetString("RelNephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nephew or niece.
        /// </summary>
        public static string RelNephewNiece {
            get {
                return ResourceManager.GetString("RelNephewNiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th {1}.
        /// </summary>
        public static string RelNFemale_2 {
            get {
                return ResourceManager.GetString("RelNFemale_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niece.
        /// </summary>
        public static string RelNiece {
            get {
                return ResourceManager.GetString("RelNiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th {1}.
        /// </summary>
        public static string RelNMale_2 {
            get {
                return ResourceManager.GetString("RelNMale_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}x removed.
        /// </summary>
        public static string RelNRemoved_en_2 {
            get {
                return ResourceManager.GetString("RelNRemoved_en_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th {1}.
        /// </summary>
        public static string RelNUnknown_2 {
            get {
                return ResourceManager.GetString("RelNUnknown_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string RelParent {
            get {
                return ResourceManager.GetString("RelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parental {0}.
        /// </summary>
        public static string RelParental_1 {
            get {
                return ResourceManager.GetString("RelParental_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibling.
        /// </summary>
        public static string RelSibling {
            get {
                return ResourceManager.GetString("RelSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        public static string RelSister {
            get {
                return ResourceManager.GetString("RelSister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string RelSon {
            get {
                return ResourceManager.GetString("RelSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son-in-law.
        /// </summary>
        public static string RelSonInLaw {
            get {
                return ResourceManager.GetString("RelSonInLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string RelSpouse {
            get {
                return ResourceManager.GetString("RelSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step child.
        /// </summary>
        public static string RelStepChild {
            get {
                return ResourceManager.GetString("RelStepChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step daughter.
        /// </summary>
        public static string RelStepDaughter {
            get {
                return ResourceManager.GetString("RelStepDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step father.
        /// </summary>
        public static string RelStepFather {
            get {
                return ResourceManager.GetString("RelStepFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step{0}.
        /// </summary>
        public static string RelStepFemale_1 {
            get {
                return ResourceManager.GetString("RelStepFemale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step{0}.
        /// </summary>
        public static string RelStepInvariant_1 {
            get {
                return ResourceManager.GetString("RelStepInvariant_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step{0}.
        /// </summary>
        public static string RelStepMale_1 {
            get {
                return ResourceManager.GetString("RelStepMale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mother.
        /// </summary>
        public static string RelStepMother {
            get {
                return ResourceManager.GetString("RelStepMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step parent.
        /// </summary>
        public static string RelStepParent {
            get {
                return ResourceManager.GetString("RelStepParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step son.
        /// </summary>
        public static string RelStepSon {
            get {
                return ResourceManager.GetString("RelStepSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncle.
        /// </summary>
        public static string RelUncle {
            get {
                return ResourceManager.GetString("RelUncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncle or aunt.
        /// </summary>
        public static string RelUncleAunt {
            get {
                return ResourceManager.GetString("RelUncleAunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string RelUnknown {
            get {
                return ResourceManager.GetString("RelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wife.
        /// </summary>
        public static string RelWife {
            get {
                return ResourceManager.GetString("RelWife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person short name format.
        /// </summary>
        public static string ShortPersonNameFormat {
            get {
                return ResourceManager.GetString("ShortPersonNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Home.
        /// </summary>
        public static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Genealogy Tree.
        /// </summary>
        public static string TitleCreateNewProjectDialog {
            get {
                return ResourceManager.GetString("TitleCreateNewProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or update {0}.
        /// </summary>
        public static string TitleCreateOrUpdateNameDialog_1 {
            get {
                return ResourceManager.GetString("TitleCreateOrUpdateNameDialog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in person information.
        /// </summary>
        public static string TitleCreateOrUpdatePersonDialog {
            get {
                return ResourceManager.GetString("TitleCreateOrUpdatePersonDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string TitleFamiliesPage {
            get {
                return ResourceManager.GetString("TitleFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string TitleNamesPage {
            get {
                return ResourceManager.GetString("TitleNamesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genealogy Tree.
        /// </summary>
        public static string TitleProjectPage {
            get {
                return ResourceManager.GetString("TitleProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        public static string TitleSelectDateDialog {
            get {
                return ResourceManager.GetString("TitleSelectDateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a name.
        /// </summary>
        public static string TitleSelectNameDialog {
            get {
                return ResourceManager.GetString("TitleSelectNameDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select relatives.
        /// </summary>
        public static string TitleSelectRelativesDialog {
            get {
                return ResourceManager.GetString("TitleSelectRelativesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string TitleSettingsPage {
            get {
                return ResourceManager.GetString("TitleSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a biography or life story....
        /// </summary>
        public static string TxtPlaceholderBiography {
            get {
                return ResourceManager.GetString("TxtPlaceholderBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Family name in the plural (for example, Smiths).
        /// </summary>
        public static string TxtPlaceholderFamilyName {
            get {
                return ResourceManager.GetString("TxtPlaceholderFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female name.
        /// </summary>
        public static string TxtPlaceholderFemaleName {
            get {
                return ResourceManager.GetString("TxtPlaceholderFemaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female last name (for example, mrs Smith).
        /// </summary>
        public static string TxtPlaceholderLastNameFemale {
            get {
                return ResourceManager.GetString("TxtPlaceholderLastNameFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male last name (mr Smith).
        /// </summary>
        public static string TxtPlaceholderLastNameMale {
            get {
                return ResourceManager.GetString("TxtPlaceholderLastNameMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male name.
        /// </summary>
        public static string TxtPlaceholderMaleName {
            get {
                return ResourceManager.GetString("TxtPlaceholderMaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female patronymic.
        /// </summary>
        public static string TxtPlaceholderPatronymicFemale {
            get {
                return ResourceManager.GetString("TxtPlaceholderPatronymicFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male patronymic.
        /// </summary>
        public static string TxtPlaceholderPatronymicMale {
            get {
                return ResourceManager.GetString("TxtPlaceholderPatronymicMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderProjectDescription {
            get {
                return ResourceManager.GetString("TxtPlaceholderProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderPtojectName {
            get {
                return ResourceManager.GetString("TxtPlaceholderPtojectName", resourceCulture);
            }
        }
    }
}
