//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT4.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GT4.UI.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete {1}?.
        /// </summary>
        public static string AlertTextDeleteConfirmationText {
            get {
                return ResourceManager.GetString("AlertTextDeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string AlertTitleConfirmation {
            get {
                return ResourceManager.GetString("AlertTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AlertTitleError {
            get {
                return ResourceManager.GetString("AlertTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string AlertTitleInfo {
            get {
                return ResourceManager.GetString("AlertTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string AlertTitleWarning {
            get {
                return ResourceManager.GetString("AlertTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genealogy Tree 4.
        /// </summary>
        public static string AppGeneralName {
            get {
                return ResourceManager.GetString("AppGeneralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own
        ///genealogy tree and enjoy!.
        /// </summary>
        public static string AppGeneralWelcomeTitle {
            get {
                return ResourceManager.GetString("AppGeneralWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing Genealogy Tree or create a new one..
        /// </summary>
        public static string BtnHintOpenOrCreateProject {
            get {
                return ResourceManager.GetString("BtnHintOpenOrCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnNameCancel {
            get {
                return ResourceManager.GetString("BtnNameCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Family.
        /// </summary>
        public static string BtnNameCreateFamily {
            get {
                return ResourceManager.GetString("BtnNameCreateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Genealogy Tree.
        /// </summary>
        public static string BtnNameCreateGenealogyTree {
            get {
                return ResourceManager.GetString("BtnNameCreateGenealogyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNameNo {
            get {
                return ResourceManager.GetString("BtnNameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BtnNameOk {
            get {
                return ResourceManager.GetString("BtnNameOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Create.
        /// </summary>
        public static string BtnNameOpenOrCreateProject {
            get {
                return ResourceManager.GetString("BtnNameOpenOrCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Refresh?.
        /// </summary>
        public static string BtnNameRefreshAfterError {
            get {
                return ResourceManager.GetString("BtnNameRefreshAfterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnNameYes {
            get {
                return ResourceManager.GetString("BtnNameYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language.
        /// </summary>
        public static string PkrLanguageHint {
            get {
                return ResourceManager.GetString("PkrLanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderProjectDescription {
            get {
                return ResourceManager.GetString("TxtPlaceholderProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderPtojectName {
            get {
                return ResourceManager.GetString("TxtPlaceholderPtojectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Home.
        /// </summary>
        public static string WndAppTitle {
            get {
                return ResourceManager.GetString("WndAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or create family.
        /// </summary>
        public static string WndHintFamiliesPage {
            get {
                return ResourceManager.GetString("WndHintFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can open the existent or create a new Genealogy Tree.
        /// </summary>
        public static string WndHintOpenOrCreateDialog {
            get {
                return ResourceManager.GetString("WndHintOpenOrCreateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Genealogy Tree.
        /// </summary>
        public static string WndTitleCreateNewProjectDialog {
            get {
                return ResourceManager.GetString("WndTitleCreateNewProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string WndTitleFamiliesPage {
            get {
                return ResourceManager.GetString("WndTitleFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Create a Genealogy.
        /// </summary>
        public static string WndTitleOpenOrCreateDialog {
            get {
                return ResourceManager.GetString("WndTitleOpenOrCreateDialog", resourceCulture);
            }
        }
    }
}
