//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT4.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GT4.UI.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete {0}?.
        /// </summary>
        public static string AlertTextDeleteConfirmationText_1 {
            get {
                return ResourceManager.GetString("AlertTextDeleteConfirmationText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string AlertTitleConfirmation {
            get {
                return ResourceManager.GetString("AlertTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AlertTitleError {
            get {
                return ResourceManager.GetString("AlertTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string AlertTitleInfo {
            get {
                return ResourceManager.GetString("AlertTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string AlertTitleWarning {
            get {
                return ResourceManager.GetString("AlertTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genealogy Tree 4.
        /// </summary>
        public static string AppGeneralName {
            get {
                return ResourceManager.GetString("AppGeneralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own
        ///genealogy tree and enjoy!.
        /// </summary>
        public static string AppGeneralWelcomeTitle {
            get {
                return ResourceManager.GetString("AppGeneralWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string BiologicalSexFemale {
            get {
                return ResourceManager.GetString("BiologicalSexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string BiologicalSexMale {
            get {
                return ResourceManager.GetString("BiologicalSexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string BiologicalSexUnknown {
            get {
                return ResourceManager.GetString("BiologicalSexUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing Genealogy Tree or create a new one..
        /// </summary>
        public static string BtnHintOpenOrCreateProject {
            get {
                return ResourceManager.GetString("BtnHintOpenOrCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add name.
        /// </summary>
        public static string BtnNameAddPersonName {
            get {
                return ResourceManager.GetString("BtnNameAddPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string BtnNameAddPersonPhoto {
            get {
                return ResourceManager.GetString("BtnNameAddPersonPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add relationship.
        /// </summary>
        public static string BtnNameAddPersonRelationship {
            get {
                return ResourceManager.GetString("BtnNameAddPersonRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnNameCancel {
            get {
                return ResourceManager.GetString("BtnNameCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Family.
        /// </summary>
        public static string BtnNameCreateFamily {
            get {
                return ResourceManager.GetString("BtnNameCreateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Person.
        /// </summary>
        public static string BtnNameCreateFamilyPerson {
            get {
                return ResourceManager.GetString("BtnNameCreateFamilyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Genealogy Tree.
        /// </summary>
        public static string BtnNameCreateGenealogyTree {
            get {
                return ResourceManager.GetString("BtnNameCreateGenealogyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNameNo {
            get {
                return ResourceManager.GetString("BtnNameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BtnNameOk {
            get {
                return ResourceManager.GetString("BtnNameOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Create.
        /// </summary>
        public static string BtnNameOpenOrCreateProject {
            get {
                return ResourceManager.GetString("BtnNameOpenOrCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Refresh?.
        /// </summary>
        public static string BtnNameRefreshAfterError {
            get {
                return ResourceManager.GetString("BtnNameRefreshAfterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the Person.
        /// </summary>
        public static string BtnNameUpdateFamilyPerson {
            get {
                return ResourceManager.GetString("BtnNameUpdateFamilyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnNameYes {
            get {
                return ResourceManager.GetString("BtnNameYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not defined.
        /// </summary>
        public static string DateStatusNotDefined {
            get {
                return ResourceManager.GetString("DateStatusNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string DateStatusUnknown {
            get {
                return ResourceManager.GetString("DateStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0}.
        /// </summary>
        public static string DateStatusYearApproximate_1 {
            get {
                return ResourceManager.GetString("DateStatusYearApproximate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional name.
        /// </summary>
        public static string FieldAdditionalName {
            get {
                return ResourceManager.GetString("FieldAdditionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age: {0}.
        /// </summary>
        public static string FieldAge_1 {
            get {
                return ResourceManager.GetString("FieldAge_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological sex.
        /// </summary>
        public static string FieldBiologicalSex {
            get {
                return ResourceManager.GetString("FieldBiologicalSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string FieldDateOfBirth {
            get {
                return ResourceManager.GetString("FieldDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of death:.
        /// </summary>
        public static string FieldDateOfDeath {
            get {
                return ResourceManager.GetString("FieldDateOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FieldFamilyName {
            get {
                return ResourceManager.GetString("FieldFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string FieldFamilyNameEntry {
            get {
                return ResourceManager.GetString("FieldFamilyNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FieldFirstName {
            get {
                return ResourceManager.GetString("FieldFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female first name.
        /// </summary>
        public static string FieldFirstNameFemaleEntry {
            get {
                return ResourceManager.GetString("FieldFirstNameFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male first name.
        /// </summary>
        public static string FieldFirstNameMaleEntry {
            get {
                return ResourceManager.GetString("FieldFirstNameMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string FieldLastName {
            get {
                return ResourceManager.GetString("FieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name in the female declension.
        /// </summary>
        public static string FieldLastNameFemaleEntry {
            get {
                return ResourceManager.GetString("FieldLastNameFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name in the male declension.
        /// </summary>
        public static string FieldLastNameMaleEntry {
            get {
                return ResourceManager.GetString("FieldLastNameMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string FieldMiddleName {
            get {
                return ResourceManager.GetString("FieldMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female middle name.
        /// </summary>
        public static string FieldMiddleNameFemaleEntry {
            get {
                return ResourceManager.GetString("FieldMiddleNameFemaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male middle name.
        /// </summary>
        public static string FieldMiddleNameMaleEntry {
            get {
                return ResourceManager.GetString("FieldMiddleNameMaleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string FieldPersonBiography {
            get {
                return ResourceManager.GetString("FieldPersonBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string FieldPersonDates {
            get {
                return ResourceManager.GetString("FieldPersonDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string FieldPersonNames {
            get {
                return ResourceManager.GetString("FieldPersonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string FieldPersonPhotos {
            get {
                return ResourceManager.GetString("FieldPersonPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string FieldPersonRelationships {
            get {
                return ResourceManager.GetString("FieldPersonRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FieldSelectName {
            get {
                return ResourceManager.GetString("FieldSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select name type.
        /// </summary>
        public static string FieldSelectNameType {
            get {
                return ResourceManager.GetString("FieldSelectNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language.
        /// </summary>
        public static string PkrLanguageHint {
            get {
                return ResourceManager.GetString("PkrLanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoptive {0}.
        /// </summary>
        public static string RelAdoptiveFemale_1 {
            get {
                return ResourceManager.GetString("RelAdoptiveFemale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoptive {0}.
        /// </summary>
        public static string RelAdoptiveMale_1 {
            get {
                return ResourceManager.GetString("RelAdoptiveMale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string RelChild {
            get {
                return ResourceManager.GetString("RelChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter.
        /// </summary>
        public static string RelDaughter {
            get {
                return ResourceManager.GetString("RelDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string RelFather {
            get {
                return ResourceManager.GetString("RelFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        public static string RelHusband {
            get {
                return ResourceManager.GetString("RelHusband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string RelMother {
            get {
                return ResourceManager.GetString("RelMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string RelSon {
            get {
                return ResourceManager.GetString("RelSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string RelSpouse {
            get {
                return ResourceManager.GetString("RelSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string RelUnknown {
            get {
                return ResourceManager.GetString("RelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wife.
        /// </summary>
        public static string RelWife {
            get {
                return ResourceManager.GetString("RelWife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Family name in the plural (for example, Smiths).
        /// </summary>
        public static string TxtPlaceholderFamilyName {
            get {
                return ResourceManager.GetString("TxtPlaceholderFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female name.
        /// </summary>
        public static string TxtPlaceholderFemaleName {
            get {
                return ResourceManager.GetString("TxtPlaceholderFemaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female last name (for example, mrs Smith).
        /// </summary>
        public static string TxtPlaceholderLastNameFemale {
            get {
                return ResourceManager.GetString("TxtPlaceholderLastNameFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male last name (mr Smith).
        /// </summary>
        public static string TxtPlaceholderLastNameMale {
            get {
                return ResourceManager.GetString("TxtPlaceholderLastNameMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male name.
        /// </summary>
        public static string TxtPlaceholderMaleName {
            get {
                return ResourceManager.GetString("TxtPlaceholderMaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter female middle name.
        /// </summary>
        public static string TxtPlaceholderMiddleNameFemale {
            get {
                return ResourceManager.GetString("TxtPlaceholderMiddleNameFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter male middle name.
        /// </summary>
        public static string TxtPlaceholderMiddleNameMale {
            get {
                return ResourceManager.GetString("TxtPlaceholderMiddleNameMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderProjectDescription {
            get {
                return ResourceManager.GetString("TxtPlaceholderProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new Genealogy Tree.
        /// </summary>
        public static string TxtPlaceholderPtojectName {
            get {
                return ResourceManager.GetString("TxtPlaceholderPtojectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Home.
        /// </summary>
        public static string WndAppTitle {
            get {
                return ResourceManager.GetString("WndAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or create family.
        /// </summary>
        public static string WndHintFamiliesPage {
            get {
                return ResourceManager.GetString("WndHintFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open family member or create a new one.
        /// </summary>
        public static string WndHintFamilyPage {
            get {
                return ResourceManager.GetString("WndHintFamilyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can open the existent or create a new Genealogy Tree.
        /// </summary>
        public static string WndHintOpenOrCreateDialog {
            get {
                return ResourceManager.GetString("WndHintOpenOrCreateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Family.
        /// </summary>
        public static string WndTitleCreateNewFamilyDialog {
            get {
                return ResourceManager.GetString("WndTitleCreateNewFamilyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Genealogy Tree.
        /// </summary>
        public static string WndTitleCreateNewProjectDialog {
            get {
                return ResourceManager.GetString("WndTitleCreateNewProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string WndTitleFamiliesPage {
            get {
                return ResourceManager.GetString("WndTitleFamiliesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Create a Genealogy.
        /// </summary>
        public static string WndTitleOpenOrCreateDialog {
            get {
                return ResourceManager.GetString("WndTitleOpenOrCreateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a name.
        /// </summary>
        public static string WndTitleSelectNameDialog {
            get {
                return ResourceManager.GetString("WndTitleSelectNameDialog", resourceCulture);
            }
        }
    }
}
